# 1) Create a new service principal in the Azure portal for your app:
# az ad sp create-for-rbac --name "myApp" --role contributor \
#   --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
#   --sdk-auth
# {
#    "clientId": "<GUID>",
#    "clientSecret": "<GUID>",
#    "subscriptionId": "<GUID>",
#    "tenantId": "<GUID>",
#    (...)
#}

# 2) Select Security > Secrets and variables > Actions.
# Paste the entire JSON output from the Azure CLI command above into the secret's value field.
# Give the secret the name AZURE_CREDENTIALS

on:
  workflow_call:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  service_principal_secret_check:
    runs-on: ubuntu-latest
    outputs:
      validated: ${{ steps.checksecret.outputs.validated }}
    steps:
      - name: Log in with Azure
        if: ${{ env.AZURE_CREDENTIALS != null }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        env:
          AZURE_CREDENTIALS: "${{ secrets.AZURE_CREDENTIALS  }}"

      - name: Azure CLI script
        if: ${{ env.AZURE_CREDENTIALS != null }}
        id: whoami
        uses: azure/CLI@v2
        inlineScript: |
          az account show
          echo "login=true" >> $GITHUB_OUTPUT
        env:
          AZURE_CREDENTIALS: "${{ secrets.AZURE_CREDENTIALS  }}"

      - name: Check secret set
        id: checksecret
        if: ${{ env.AZURE_CREDENTIALS != null }}
        run: |
          set -x
          echo "validated=true" >> $GITHUB_OUTPUT
