on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  managed_service_identity_check:
    runs-on: ubuntu-latest
    outputs:
      validated: ${{ steps.checksecret.outputs.validated }}

    steps:
      - name: Az CLI login with OIDC
        if: ${{ env.ARM_CLIENT_ID != null && env.ARM_SUBSCRIPTION_ID != null && env.ARM_TENANT_ID != null }}
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

      - name: Azure whoami CLI script
        if: ${{ env.ARM_CLIENT_ID != null && env.ARM_SUBSCRIPTION_ID != null && env.ARM_TENANT_ID != null }}
        id: whoami
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            echo "login=true" >> $GITHUB_OUTPUT
        env:
          ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

      - name: Secrets are validated
        id: checksecret
        if: ${{ steps.whoami.output.login == true }}
        run: |
          set -x
          echo "validated=true" >> $GITHUB_OUTPUT
